---
title: Training Ballarat
email: Charles.TrainingBallarat@gmail.com
phone: 
tag: Training makes a world of difference
description: > # this means to ignore newlines until "baseurl:"
  ABN <i class="fa fa-fax"></i> 70 242 719 901
  <br>
  Workplace Training, Office Management and Staff Analysis.
twitter_username:
github_username:
website_design: //jmilne.com.au
website_design_name: jm | Design
---
